### ISSUE TITLE
First Artboard/Symbol placement

### ISSUE THREAD

**Issue by Okkido** [richardgazdik/sketch-align#1]
It would be great if the first aligned Artboard/Symbol would be placed on x 0, y 0 position instead of a random (calculated from the height of the first symbol?) x and y position.

**Comment by richardgazdik** [comment]
If the first artboard's position is not 0,0 then it's a bug and i'm going to fix it soon. Sometimes Sketch is not updating the UI of rulers and you need to switch between pages to see the changes.
